const state={items:[],filter:"all",query:"",editingNoteId:null};
const el={items:document.querySelector("#items"),search:document.querySelector("#search"),connection:document.querySelector("#connection"),storage:document.querySelector("#storage"),fileInput:document.querySelector("#file-input"),dropZone:document.querySelector("#drop-zone"),progress:document.querySelector("#upload-progress"),dialog:document.querySelector("#note-dialog"),noteForm:document.querySelector("#note-form"),noteTitle:document.querySelector("#note-title"),noteContent:document.querySelector("#note-content"),dialogTitle:document.querySelector("#note-dialog-title"),toast:document.querySelector("#toast")};

function formatBytes(bytes){const units=["B","KB","MB","GB","TB"];let value=Number(bytes||0),unit=0;while(value>=1024&&unit<units.length-1){value/=1024;unit++}return`${value.toFixed(unit<2?0:1)} ${units[unit]}`}
function formatDate(value){if(!value)return"Now";const normalized=value.includes("T")?value:`${value.replace(" ","T")}Z`;return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(normalized))}
function toast(message,isError=false){el.toast.textContent=message;el.toast.classList.toggle("error",isError);el.toast.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.toast.classList.remove("show"),2800)}
async function api(url,options={}){const response=await fetch(url,options);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||`Request failed (${response.status})`);return payload}
function icon(item){
  if(item.type==="note")return"TXT";
  const typeMap={image:"IMG",video:"VID",audio:"AUD",document:"DOC",file:"FILE"};
  if(typeMap[item.type])return typeMap[item.type];
  const extension=item.title.split(".").pop();
  return extension&&extension!==item.title?extension.slice(0,4):"FILE";
}
function visibleItems(){return state.items.filter(item=>{if(state.filter==="all")return true;if(state.filter==="note")return item.type==="note";return item.type!=="note"})}

function render(){
  const items=visibleItems(),notes=state.items.filter(item=>item.type==="note").length,files=state.items.filter(item=>item.type!=="note").length;
  document.querySelector("#all-count").textContent=state.items.length;document.querySelector("#file-count").textContent=files;document.querySelector("#note-count").textContent=notes;
  document.querySelector("#item-summary").textContent=`${items.length} item${items.length===1?"":"s"}`;el.items.replaceChildren();
  if(!items.length){const empty=document.createElement("div"),title=document.createElement("strong"),detail=document.createElement("span");empty.className="empty";title.textContent=state.query?"Nothing matched that search":"This space is ready";detail.textContent=state.query?"Try another word or clear the search.":"Send a file or write your first note.";empty.append(title,detail);el.items.append(empty);return}
  for(const item of items){
    const row=document.createElement("button"),badge=document.createElement("span"),body=document.createElement("span"),title=document.createElement("span"),preview=document.createElement("span"),meta=document.createElement("span");
    row.type="button";row.className="item";row.dataset.id=item.id;badge.className="item-icon";if(["image","video","audio","document"].includes(item.type))badge.classList.add("type-"+item.type);badge.textContent=icon(item);title.className="item-title";title.textContent=item.title;preview.className="item-preview";preview.textContent=item.type==="note"?(item.content||"Empty note"):`${item.mediaType||"File"} · ${formatBytes(item.byteSize)}`;body.append(title,preview);meta.className="item-meta";meta.textContent=`${formatDate(item.updatedAt)}\n${item.type==="note"?"Open note":"Download"}`;meta.style.whiteSpace="pre-line";row.append(badge,body,meta);el.items.append(row)
  }
}

async function loadItems(){try{const suffix=state.query?`?q=${encodeURIComponent(state.query)}`:"";const result=await api(`/api/v1/items${suffix}`);state.items=result.items||[];render()}catch(error){el.items.replaceChildren();const box=document.createElement("div");box.className="empty";box.textContent=`Could not load the inbox: ${error.message}`;el.items.append(box)}}
function openNote(item=null){state.editingNoteId=item?.id||null;el.dialogTitle.textContent=item?"Edit note":"New note";el.noteTitle.value=item?.title||"";el.noteContent.value=item?.content||"";el.dialog.showModal();setTimeout(()=>item?el.noteContent.focus():el.noteTitle.focus(),0)}

function uploadOne(file){return new Promise((resolve,reject)=>{const form=new FormData(),xhr=new XMLHttpRequest();form.append("file",file);xhr.open("POST","/api/v1/files");xhr.upload.addEventListener("progress",event=>{if(event.lengthComputable)el.progress.textContent=`${file.name} · ${Math.round(event.loaded/event.total*100)}%`});xhr.addEventListener("load",()=>xhr.status>=200&&xhr.status<300?resolve():reject(new Error(`Upload failed (${xhr.status})`)));xhr.addEventListener("error",()=>reject(new Error("The upload connection failed")));xhr.send(form)})}
async function uploadFiles(files){const list=[...files];if(!list.length)return;try{for(const file of list)await uploadOne(file);toast(`${list.length} file${list.length===1?"":"s"} stored on the host`);await loadItems()}catch(error){toast(error.message,true)}finally{el.progress.textContent="";el.fileInput.value=""}}

document.querySelector("#send-file").addEventListener("click",()=>el.fileInput.click());document.querySelector("#new-note").addEventListener("click",()=>openNote());document.querySelector("#close-note").addEventListener("click",()=>el.dialog.close());el.fileInput.addEventListener("change",()=>uploadFiles(el.fileInput.files));
el.dropZone.addEventListener("dragover",event=>{event.preventDefault();el.dropZone.classList.add("dragging")});el.dropZone.addEventListener("dragleave",()=>el.dropZone.classList.remove("dragging"));el.dropZone.addEventListener("drop",event=>{event.preventDefault();el.dropZone.classList.remove("dragging");uploadFiles(event.dataTransfer.files)});
el.items.addEventListener("click",event=>{const row=event.target.closest(".item");if(!row)return;const item=state.items.find(candidate=>candidate.id===row.dataset.id);if(!item)return;if(item.type==="note")openNote(item);else window.location.assign(item.downloadUrl)});
el.noteForm.addEventListener("submit",async event=>{event.preventDefault();const payload=JSON.stringify({title:el.noteTitle.value.trim(),content:el.noteContent.value}),url=state.editingNoteId?`/api/v1/notes/${state.editingNoteId}`:"/api/v1/notes";try{await api(url,{method:state.editingNoteId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:payload});el.dialog.close();toast(state.editingNoteId?"Note updated":"Note created");await loadItems()}catch(error){toast(error.message,true)}});
let searchTimer;el.search.addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=el.search.value.trim();loadItems()},220)});
document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".nav-item").forEach(item=>item.classList.remove("active"));button.classList.add("active");state.filter=button.dataset.filter;const labels={all:["Everything","Files and thoughts from every device, in one place."],file:["Files","Media and documents stored by the host."],note:["Notes","Thoughts that follow you across devices."]};document.querySelector("#view-title").textContent=labels[state.filter][0];document.querySelector("#view-description").textContent=labels[state.filter][1];render()}));

function connectEvents(){const protocol=location.protocol==="https:"?"wss:":"ws:",socket=new WebSocket(`${protocol}//${location.host}/api/v1/events`);socket.addEventListener("open",()=>{el.connection.textContent="Host online";el.connection.classList.add("online")});socket.addEventListener("message",event=>{try{if(JSON.parse(event.data).type==="items.changed")loadItems()}catch{}});socket.addEventListener("close",()=>{el.connection.textContent="Reconnecting";el.connection.classList.remove("online");setTimeout(connectEvents,2000)})}
api("/api/v1/system").then(system=>{el.storage.textContent=`${formatBytes(system.storage.availableBytes)} free`}).catch(()=>{el.storage.textContent="Storage unavailable"});loadItems();connectEvents();
