const list = document.querySelector("#recycle-list");
const toastNode = document.querySelector("#toast");
const connection = document.querySelector("#connection");
const summary = document.querySelector("#item-summary");
let toastTimer;

function toast(message, error = false) { toastNode.textContent = message; toastNode.classList.toggle("error", error); toastNode.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => toastNode.classList.remove("show"), 2800); }
async function api(url, options = {}) { const response = await fetch(url, options); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || `Request failed (${response.status})`); return body; }
function formatBytes(bytes) { const units = ["B", "KB", "MB", "GB"]; let value = Number(bytes || 0), index = 0; while (value >= 1024 && index < units.length - 1) { value /= 1024; index++; } return `${value.toFixed(index ? 1 : 0)} ${units[index]}`; }
function row(kind, entry) { const item = document.createElement("article"); item.className = "recycle-row"; const body = document.createElement("div"); body.className = "task-body"; const title = document.createElement("strong"); title.textContent = entry.title || "Untitled"; const meta = document.createElement("small"); meta.textContent = kind === "items" ? `${entry.type} · ${formatBytes(entry.byteSize)}` : `Task · ${entry.status}`; body.append(title, meta); const actions = document.createElement("div"); actions.className = "task-actions"; const restore = document.createElement("button"); restore.className = "button secondary"; restore.textContent = "Restore"; restore.onclick = () => restoreEntry(kind, entry.id); const purge = document.createElement("button"); purge.className = "button danger"; purge.textContent = "Delete forever"; purge.onclick = () => purgeEntry(kind, entry.id); actions.append(restore, purge); item.append(body, actions); return item; }
function render(data) { const items = data.items || [], tasks = data.tasks || [], total = items.length + tasks.length; summary.textContent = `${total} item${total === 1 ? "" : "s"}`; list.replaceChildren(); if (!total) { const empty = document.createElement("div"); empty.className = "empty"; empty.textContent = "The recycle bin is empty."; list.append(empty); return; } items.forEach(entry => list.append(row("items", entry))); tasks.forEach(entry => list.append(row("tasks", entry))); }
async function load() { try { render(await api("/api/v1/recycle-bin")); } catch (error) { list.replaceChildren(); const empty = document.createElement("div"); empty.className = "empty"; empty.textContent = `Could not load the recycle bin: ${error.message}`; list.append(empty); } }
async function restoreEntry(kind, id) { try { await api(`/api/v1/recycle-bin/${kind}/${id}/restore`, {method: "POST"}); toast("Restored"); await load(); } catch (error) { toast(error.message, true); } }
async function purgeEntry(kind, id) { if (!window.confirm("Delete permanently? This cannot be undone.")) return; try { await api(`/api/v1/recycle-bin/${kind}/${id}`, {method: "DELETE"}); toast("Deleted permanently"); await load(); } catch (error) { toast(error.message, true); } }
function connect() { const protocol = location.protocol === "https:" ? "wss:" : "ws:", socket = new WebSocket(`${protocol}//${location.host}/api/v1/events`); socket.addEventListener("open", () => { connection.textContent = "Host online"; connection.classList.add("online"); }); socket.addEventListener("message", event => { try { const message = JSON.parse(event.data); if (message.type === "items.changed" || message.type === "tasks.changed" || message.type === "recycle.changed") load(); } catch {} }); socket.addEventListener("close", () => { connection.textContent = "Reconnecting"; connection.classList.remove("online"); setTimeout(connect, 2000); }); }
load(); connect();
